version: "3"
services:
  broker:
    image: rmohr/activemq
    ports:
      - 61616:61616
      - 61613:61613
      - 8161:8161
  platform:
    image: ld4p/trellis-ext-db:latest
    environment:
      TRELLIS_BASE_URL: http://platform:8080
      TRELLIS_LOGGING_LEVEL: INFO
      TRELLIS_CONSOLE_LOGGING_THRESHOLD: INFO
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - database
      - broker
      - migration
  pipeline:
    build:
      context: .
    environment:
      INDEX_HOST: search
      BROKER_HOST: broker
    command: dockerize -wait tcp://broker:61613 -wait tcp://search:9200 -timeout 3m npm start
    depends_on:
      - broker
      - search
      - platform
  integration:
    build:
      context: .
    environment:
      INDEX_HOST: search
      BROKER_HOST: broker
      INSIDE_CONTAINER: 'true'
    command: dockerize -wait tcp://broker:61613 -wait tcp://search:9200 -wait tcp://platform:8080 -timeout 3m npm run integration
    depends_on:
      - pipeline
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: sinopia
      POSTGRES_DB: sinopia
      POSTGRES_PASSWORD: S1n0p1a
      PGDATA: /var/lib/postgresql/data/pgdata/mydata
    ports:
      - 5432:5432
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    entrypoint:
      - elasticsearch
      - -Ehttp.port=9200
      - -Ehttp.cors.enabled=true
      - -Ehttp.cors.allow-origin=http://searchui:1358,http://localhost:1358,http://127.0.0.1:1358
      - -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - -Ehttp.cors.allow-credentials=true
      - -Etransport.host=localhost
      - -Ebootstrap.system_call_filter=false
    user: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
  searchui:
    image: appbaseio/dejavu:latest
    ports:
      - 1358:1358
    depends_on:
      - search
  migration:
    image: ld4p/trellis-ext-db:latest
    command: ["/opt/trellis/bin/trellis-db", "db", "migrate", "/opt/trellis/etc/config.yml"]
    depends_on:
      - database
