version: "3"
services:
  pipeline:
    build:
      context: .
    image: ld4p/sinopia_indexing_pipeline:latest
    environment:
      INDEX_URL: http://search:9200
      BROKER_HOST: broker
    depends_on:
      - search
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
      - 28017:28017
    environment:
      MONGO_INITDB_ROOT_USERNAME: sinopia
      MONGO_INITDB_ROOT_PASSWORD: sekret
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo-setup:
    image: ld4p/sinopia_dev_setup:latest
    # Replace image with build to build from local code. Do not commit docker-compose.yml.
    # build:
    #   context: ../sinopia_api
    #   dockerfile: Dockerfile-setup
    depends_on:
      - mongo
  reindexer:
    build:
      context: .
    environment:
      INDEX_URL: http://search:9200
      BROKER_HOST: broker
      INSIDE_CONTAINER: 'true'
    command: bin/reindex
    depends_on:
      - pipeline
  search:
    image: ld4p/sinopia_elasticsearch:latest
    entrypoint:
      - elasticsearch
      - -Ehttp.port=9200
      - -Ehttp.cors.enabled=true
      - -Ehttp.cors.allow-origin=http://searchui:1358,http://localhost:1358,http://127.0.0.1:1358
      - -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - -Ehttp.cors.allow-credentials=true
      - -Etransport.host=localhost
      - -Ebootstrap.system_call_filter=false
    user: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
  searchui:
    image: appbaseio/dejavu:latest
    ports:
      - 1358:1358
    depends_on:
      - search
